test_environment:
  headers:
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjUwMCwicmlkIjowLCJpYXQiOjE3MzAyOTAzNTYsImV4cCI6MTczMDM3Njc1Nn0.MgGQti5XEFS0iyDjtjG0v-VmD3a5haae6sZD0_SGg3s
    Content-Type: null
    accept-language: zh-CN,zh;q=0.9
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,like
      Gecko) Chrome/104.0.0.0 Safari/537.36
  host: http://127.0.0.1:8888
